In [ ]:
#Ref from ankitbansal tutorials

In [31]:
!pip install kaggle

Requirement already satisfied: kaggle in c:\users\mouni\anaconda3\lib\site-packages (2.1.2)
Requirement already satisfied: bleach in c:\users\mouni\anaconda3\lib\site-packages (from kaggle) (4.1.0)
Requirement already satisfied: jupytext in c:\users\mouni\anaconda3\lib\site-packages (from kaggle) (1.19.1)
Requirement already satisfied: kagglesdk<1.0,>=0.1.23 in c:\users\mouni\anaconda3\lib\site-packages (from kaggle) (0.1.23)
Requirement already satisfied: packaging in c:\users\mouni\anaconda3\lib\site-packages (from kaggle) (23.1)
Requirement already satisfied: protobuf in c:\users\mouni\anaconda3\lib\site-packages (from kaggle) (7.34.1)
Requirement already satisfied: python-dateutil in c:\users\mouni\anaconda3\lib\site-packages (from kaggle) (2.8.2)
Requirement already satisfied: python-slugify in c:\users\mouni\anaconda3\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: requests in c:\users\mouni\anaconda3\lib\site-packages (from kaggle) (2.31.0)
Requirement already satisfied: tqdm in c:\users\mouni\anaconda3\lib\site-packages (from kaggle) (4.65.0)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\mouni\anaconda3\lib\site-packages (from kaggle) (1.26.16)
Requirement already satisfied: six>=1.9.0 in c:\users\mouni\anaconda3\lib\site-packages (from bleach->kaggle) (1.16.0)
Requirement already satisfied: webencodings in c:\users\mouni\anaconda3\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in c:\users\mouni\anaconda3\lib\site-packages (from jupytext->kaggle) (2.2.0)
Requirement already satisfied: mdit-py-plugins in c:\users\mouni\anaconda3\lib\site-packages (from jupytext->kaggle) (0.3.0)
Requirement already satisfied: nbformat in c:\users\mouni\anaconda3\lib\site-packages (from jupytext->kaggle) (5.9.2)
Requirement already satisfied: pyyaml in c:\users\mouni\anaconda3\lib\site-packages (from jupytext->kaggle) (6.0)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\mouni\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\mouni\anaconda3\lib\site-packages (from requests->kaggle) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mouni\anaconda3\lib\site-packages (from requests->kaggle) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mouni\anaconda3\lib\site-packages (from requests->kaggle) (2023.7.22)
Requirement already satisfied: colorama in c:\users\mouni\anaconda3\lib\site-packages (from tqdm->kaggle) (0.4.6)
Requirement already satisfied: mdurl~=0.1 in c:\users\mouni\anaconda3\lib\site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.0)
Requirement already satisfied: fastjsonschema in c:\users\mouni\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (2.16.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\mouni\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (4.17.3)
Requirement already satisfied: jupyter-core in c:\users\mouni\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (5.3.0)
Requirement already satisfied: traitlets>=5.1 in c:\users\mouni\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=17.4.0 in c:\users\mouni\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (22.1.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\mouni\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.18.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\mouni\anaconda3\lib\site-packages (from jupyter-core->nbformat->jupytext->kaggle) (4.9.6)
Requirement already satisfied: pywin32>=300 in c:\users\mouni\anaconda3\lib\site-packages (from jupyter-core->nbformat->jupytext->kaggle) (305.1)

In [1]:
# download from kaggle to local download folder
import kaggle
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
orders.csv.zip: Skipping, found more recently modified local copy (use --force to force download)

In [2]:
#extract a zipefile , using zipfile.Zipfile

import zipfile
with zipfile.ZipFile("orders.csv.zip", "r")  as zipref:
    zipref.extractall()

In [6]:
import pandas as pd

data =pd.read_csv('orders.csv',na_values=['Not Available','unknown','null'])
# data.head(5)
# data

data['Ship Mode'].unique()
# data['Ship Mode'].unique().na_values('Not Available','unknown',null)

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [7]:
data['Ship Mode'].unique()
# data['Ship Mode'].unique().na_values('Not Available','unknown',null)

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [ ]:
#handling notavialble and unknown using na_values
df =pd.read_csv('orders.csv',na_values=['Not Available','unknown'])
# data.head(5)
# data

df['Ship Mode'].unique()

In [9]:
#rename columns
# df.rename(columns={})
# df.columns returns a index Object
data.columns =data.columns.str.lower().str.replace(' ','_')
# df2 =df1.columns.replace(' ','_')
# df.columns = df.columns.replace(' ','_')
data

# df.columns

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [11]:
#derive new columns discount, saleprice and profit

data['discount']= data['list_price']*data['discount_percent']*.01

# df[listprice*discount_percent*.01
data['saleprice']=data['list_price']-data['discount']
data['profit'] =data['saleprice']-data['cost_price']
# df.type()
#profit = saleice -costprice

In [13]:
data.dtypes

data['order_date']= pd.to_datetime(data['order_date'],format="%Y-%m-%d")
data.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
saleprice                  float64
profit                     float64
dtype: object

In [15]:
data.drop(columns=['list_price','cost_price','discount_percent'],inplace= True)

In [28]:
!pip install pymysql

Collecting pymysql
  Obtaining dependency information for pymysql from https://files.pythonhosted.org/packages/8e/dc/9085f3d6f497e9b25fb40d6e8ecef3ddbb5cf977a949b933624a299f5c16/pymysql-1.1.3-py3-none-any.whl.metadata
  Downloading pymysql-1.1.3-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.3-py3-none-any.whl (45 kB)
   ---------------------------------------- 0.0/45.4 kB ? eta -:--:--
   --------- ------------------------------ 10.2/45.4 kB ? eta -:--:--
   ------------------ --------------------- 20.5/45.4 kB 217.9 kB/s eta 0:00:01
   ---------------------------------------- 45.4/45.4 kB 373.6 kB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.3

In [29]:
import pandas as pdf
from sqlalchemy import create_engine 
cnx = create_engine("mysql+pymysql://root:root@localhost:3306/tables")    
df = pd.read_sql("SELECT * FROM employees",cnx)
df

,emp_id,emp_name,dept_id,manager_id,salary,hire_date,job_title
0,1,John,10,NaN,90000,2018-01-10,Manager
1,2,Sara,10,1.0,70000,2019-03-15,Developer
2,3,Amit,20,5.0,60000,2020-05-20,Developer
3,4,Lina,30,1.0,75000,2017-09-11,Analyst
4,5,Raj,20,NaN,95000,2016-12-05,Manager
5,6,Dev,30,1.0,72000,2021-04-18,Analyst
6,7,Kim,10,1.0,50000,2022-02-02,Intern
7,8,Jill,20,5.0,85000,2019-07-22,Lead
8,9,rohit,20,5.0,90000,2019-07-23,Lead
9,10,kunal,20,5.0,100000,2019-07-24,SR engineer
10,11,RK,20,5.0,110000,2016-12-04,Sr software engineer
11,5,Raj,30,NaN,95000,2016-12-05,Manager

In [30]:
#load data in tomysql
df.to_sql('df_orders',con=cnx,index=False,if_exists='replace')

12